import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const epoch = localFont({
  src: "../public/fonts/Epoch-BF6881cf42e6637.otf",
  variable: "--font-epoch",
  display: "swap",
});

const gilroy = localFont({
  src: "../public/fonts/gilroy-medium.ttf",
  variable: "--font-gilroy",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${epoch.variable} ${gilroy.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
